"""
Puertos por defecto asigandos a cada agente.
"""

# Por orden de ejecución
PUERTO_DIRECTORIO = 9000
PUERTO_INFO_TRANSPORTE = 9001
PUERTO_INFO_ALOJAMIENTO_AMADEUS = 9002
PUERTO_INFO_ALOJAMIENTO_TOURPEDIA = 9003
PUERTO_INFO_ACTIVIDADES = 9004
PUERTO_GESTOR_TRANSPORTE = 9005
PUERTO_GESTOR_ALOJAMIENTO = 9006
PUERTO_GESTOR_ACTIVIDADES = 9007
PUERTO_UNIFICADOR = 9008